# Generated by Django 2.0.1 on 2018-02-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default=0)),
                ('emp_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_addr', models.CharField(max_length=200)),
                ('empdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_details.EmpData')),
            ],
        ),
    ]
