# Generated by Django 2.0.1 on 2018-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], default='L', max_length=1),
            preserve_default=False,
        ),
    ]
