# Generated by Django 2.0.1 on 2018-02-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0005_auto_20180209_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdesc',
            name='empdata',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='EmpData',
        ),
        migrations.DeleteModel(
            name='EmpDesc',
        ),
    ]
